
kind: pipeline
name: drone_test
steps:
  - name: gobuild
    image: golang:1.16
    environment:
       GOOS: linux
       GOPROXY: https://goproxy.cn,direct
       GOPATH: /drone/src/gopath
    commands:
      - go mod tidy && go mod download
      - go build -ldflags="-w -s" -o  drone_test
  - name: dev250_scp
    image: appleboy/drone-scp
    settings:
      host: 27.54.253.250
      username: root
      password: ~idc88121212
      port: 22
      target: /root/drone_test
      source: drone_test
trigger:
  branch:
    - main
